const skills = [
  { name: "Next.JS", image: "./assets/nextdotjs.svg" },
  { name: "React.JS", image: "./assets/react.svg" },
  { name: "Typescript", image: "./assets/typescript.svg" },
  { name: "ReactQuery", image: "./assets/reactquery.svg" },
  { name: "Java", image: "./assets/bxl-java.svg" },
  { name: "Spring", image: "./assets/spring.svg" },
  { name: "SpringBoot", image: "./assets/springboot.svg" },
  { name: "MySQL", image: "./assets/mysql.svg" },
  { name: "MongoDB", image: "./assets/mongodb.svg" },
  { name: "Firebase", image: "./assets/firebase.svg" },
  { name: "Hibernate", image: "./assets/hibernate.svg" },
  { name: "Node.JS", image: "./assets/nodedotjs.svg" },
  { name: "Figma", image: "./assets/figma.svg" },
  { name: "HTML5", image: "./assets/html5.svg" },
  { name: "CSS3", image: "./assets/css3.svg" },
  { name: "Javascript", image: "./assets/javascript.svg" },
  { name: "Git", image: "./assets/git.svg" },
  { name: "Docker", image: "./assets/docker.svg" },
  { name: "Material UI", image: "./assets/mui.svg" },
  { name: "Bootstrap", image: "./assets/bootstrap.svg" },
  { name: "SASS", image: "./assets/sass.svg" },
  { name: "Jira", image: "./assets/jirasoftware.svg" },
  { name: "Trello", image: "./assets/trello.svg" },
  { name: "Redux", image: "./assets/redux.svg" },
  { name: "Testing", image: "./assets/testinglibrary.svg" },
  { name: "Postman", image: "./assets/postman.svg" },
];

const carousel = new Carousel(skills);
carousel.init();
